config/routes.rb
Rails.application.routes.draw do
  resources :blogs
	root 'pages#home'
  resources :posts
  post "/posts/upload_image/:id", to: "posts#upload_image", as: :upload_post_image 
  post "/blogs/upload_image/:id", to: "blogs#upload_image", as: :upload_blog_image 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	has_many_attached :images 
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :post

  has_attached_file :image,
    storage: :s3,
    :url => ':s3_alias_url',
    :s3_host_alias => "Enter Your ColudFront URL",
    path: "posts/pictures/:id/:style/:filename",
    s3_credentials: {
      bucket: "Enter Your bucket name",
      access_key_id: "Enter Your access_key_id",
      secret_access_key: "Enter Your secret_access_key",
      s3_region: "Enter Your s3_region"
    },
    s3_permissions: {
      original: "public-read"
    }
  do_not_validate_attachment_file_type :image
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :pictures, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy,:upload_image]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upload_image
    @blog.images.attach(params[:images])
    redirect_to blog_path(@blog.id), notice: 'image was successfully uploaded.'
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:blog_title, :blog_body,:images)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upload_image]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        @post.pictures.create(image: params[:images])
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def upload_image
    @post.pictures.create(image: params[:images])
    redirect_to post_path(@post.id), notice: 'image was successfully uploaded.'
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:post_title, :post_body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :blog_title %>
    <%= form.text_field :blog_title %>
  </div>

  <div class="field">
    <%= form.label :blog_body %>
    <%= form.text_field :blog_body %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.text_field :post_title %>
    <%= form.file_field :images %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Blog title</th>
      <th>Blog body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.blog_title %></td>
        <td><%= blog.blog_body %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag upload_blog_image_path(@blog.id), multipart: true  do %>
<%= file_field_tag "images", type: :file %>
<%= submit_tag %>
<% end %>
<p>
  <strong>Blog title:</strong>
  <%= @blog.blog_title %>
</p>


<style>
	.btn:focus, .btn:active, button:focus, button:active {
  outline: none !important;
  box-shadow: none !important;
}

#image-gallery .modal-footer{
  display: block;
}

.thumb{
  margin-top: 15px;
  margin-bottom: 15px;
}

</style>
<div class="container">
	<div class="row">
		<div class="row">
            <% @blog.images.each do |image| %>
            <div class="col-lg-4 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" data-image-id="" data-toggle="modal" data-title="Im so nice" data-target = "#image-gallery"
                   data-image="<%= url_for(image.service_url.sub('thinkbiz-paperclip-demo-bucket.s3.ap-south-1.amazonaws.com','d2r2t95iem61ar.cloudfront.net'))%> ">
                   <!--  <img class=""
                         src="https://images.pexels.com/photos/158971/pexels-photo-158971.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"
                         alt="Another alt text"> -->
                         <%= image_tag url_for(image.service_url.sub('thinkbiz-paperclip-demo-bucket.s3.ap-south-1.amazonaws.com','d2r2t95iem61ar.cloudfront.net') ) , :style => "width:300px;height:300px", :class => "img-thumbnail"  %>
                </a>
            </div>
            <% end %>
        </div>


        <div class="modal fade" id="image-gallery" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="image-gallery-title"></h4>
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <img id="image-gallery-image" class="img-responsive col-md-12" src="">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary float-left" id="show-previous-image"><i class="fa fa-arrow-left"></i>
                        </button>

                        <button type="button" id="show-next-image" class="btn btn-secondary float-right"><i class="fa fa-arrow-right"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
	</div>
</div>

<script>
	//let $('#image-gallery') = $('#image-gallery');
	$(document)
	.ready(function () {

		loadGallery(true, 'a.thumbnail');

    //This function disables buttons when needed
    function disableButtons(counter_max, counter_current) {
    	$('#show-previous-image, #show-next-image').show();
    	if (counter_max === counter_current) {
    		$('#show-next-image').hide();
    	} else if (counter_current === 1) {
    		$('#show-previous-image').hide();
    	}
    }

    /**
     *
     * @param setIDs        Sets IDs when DOM is loaded. If using a PHP counter, set to false.
     * @param setClickAttr  Sets the attribute for the click handler.
     */

     function loadGallery(setIDs, setClickAttr) {
     	let current_image,
     	selector,
     	counter = 0;

     	$('#show-next-image, #show-previous-image').click(function () {
     		if ($(this).attr('id') === 'show-previous-image') {
     			current_image--;
	     	} else {
	     		current_image++;
     	}

     	selector = $('[data-image-id="' + current_image + '"]');
     	updateGallery(selector);
     });

     	function updateGallery(selector) {
     		let $sel = selector;
     		current_image = $sel.data('image-id');
     		$('#image-gallery-title').text($sel.data('title'));
     		$('#image-gallery-image').attr('src', $sel.data('image'));
     		$('#image-gallery-image').css({"height": "300px"});
     		disableButtons(counter, $sel.data('image-id'));
     	}

     	if (setIDs == true) {
     		$('[data-image-id]').each(function () {
     			counter++;
     			$(this).attr('data-image-id', counter);
     		});
     	}
     	$(setClickAttr).on('click', function () {
     		updateGallery($(this));
     	});
     }
   });

// build key actions
$(document)
.keydown(function (e) {
	switch (e.which) {
      case 37: // left
      if (($('#image-gallery').data('bs.modal') || {})._isShown && $('#show-previous-image').is(":visible")) {
      	$('#show-previous-image').click();
      }
      break;

      case 39: // right
      if (($('#image-gallery').data('bs.modal') || {})._isShown && $('#show-next-image').is(":visible")) {
      	$('#show-next-image').click();
      }
      break;

      default:
        return; // exit this handler for other keys
      }
    e.preventDefault(); // prevent the default action (scroll / move caret)
  });

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeperClipDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Upload Images with PaperClip and Active storage</h1>


<%= link_to "Upload Images with PaperClip", posts_path, class: "btn btn-primary" %>
<%= link_to "Upload Images with Active Storage", blogs_path, class: "btn btn-secondary" %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true,multipart: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :post_title %>
    <%= form.text_field :post_title %>
    <%= file_field_tag "images", type: :file %>
  </div>

  <div class="field">
    <%= form.label :post_body %>
    <%= form.text_field :post_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Post title</th>
      <th>Post body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.post_title %></td>
        <td><%= post.post_body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag upload_post_image_path(@post.id), multipart: true  do %>
<%= file_field_tag "images", type: :file %>
<%= submit_tag %>
<% end %>
<p>
  <strong>Post title:</strong>
  <%= @post.post_title %>
</p>

<!-- <p>
  <strong>Post body:</strong>
  <%= @post.post_body %>
  <% @post.pictures.each do |picture| %>
  <%= image_tag picture.image.url , :style => "width:300px;height:300px"  %>
  <% end %>
</p> -->
<style>
	.btn:focus, .btn:active, button:focus, button:active {
  outline: none !important;
  box-shadow: none !important;
}

#image-gallery .modal-footer{
  display: block;
}

.thumb{
  margin-top: 15px;
  margin-bottom: 15px;
}

</style>
<div class="container">
	<div class="row">
		<div class="row">
            <% @post.pictures.each do |picture| %>
            <div class="col-lg-4 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" data-image-id="" data-toggle="modal" data-title="Im so nice" data-target = "#image-gallery"
                   data-image="<%= picture.image.url%> ">
                   <!--  <img class=""
                         src="https://images.pexels.com/photos/158971/pexels-photo-158971.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"
                         alt="Another alt text"> -->
                         <%= image_tag picture.image.url , :style => "width:300px;height:300px", :class => "img-thumbnail"  %>
                </a>
            </div>
            <% end %>
        </div>


        <div class="modal fade" id="image-gallery" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="image-gallery-title"></h4>
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <img id="image-gallery-image" class="img-responsive col-md-12" src="">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary float-left" id="show-previous-image"><i class="fa fa-arrow-left"></i>
                        </button>

                        <button type="button" id="show-next-image" class="btn btn-secondary float-right"><i class="fa fa-arrow-right"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
	</div>
</div>

<script>
	//let $('#image-gallery') = $('#image-gallery');
	$(document)
	.ready(function () {

		loadGallery(true, 'a.thumbnail');

    //This function disables buttons when needed
    function disableButtons(counter_max, counter_current) {
    	$('#show-previous-image, #show-next-image').show();
    	if (counter_max === counter_current) {
    		$('#show-next-image').hide();
    	} else if (counter_current === 1) {
    		$('#show-previous-image').hide();
    	}
    }

    /**
     *
     * @param setIDs        Sets IDs when DOM is loaded. If using a PHP counter, set to false.
     * @param setClickAttr  Sets the attribute for the click handler.
     */

     function loadGallery(setIDs, setClickAttr) {
     	let current_image,
     	selector,
     	counter = 0;

     	$('#show-next-image, #show-previous-image').click(function () {
     		if ($(this).attr('id') === 'show-previous-image') {
     			current_image--;
	     	} else {
	     		current_image++;
     	}

     	selector = $('[data-image-id="' + current_image + '"]');
     	updateGallery(selector);
     });

     	function updateGallery(selector) {
     		let $sel = selector;
     		current_image = $sel.data('image-id');
     		$('#image-gallery-title').text($sel.data('title'));
     		$('#image-gallery-image').attr('src', $sel.data('image'));
     		$('#image-gallery-image').css({"height": "300px"});
     		disableButtons(counter, $sel.data('image-id'));
     	}

     	if (setIDs == true) {
     		$('[data-image-id]').each(function () {
     			counter++;
     			$(this).attr('data-image-id', counter);
     		});
     	}
     	$(setClickAttr).on('click', function () {
     		updateGallery($(this));
     	});
     }
   });

// build key actions
$(document)
.keydown(function (e) {
	switch (e.which) {
      case 37: // left
      if (($('#image-gallery').data('bs.modal') || {})._isShown && $('#show-previous-image').is(":visible")) {
      	$('#show-previous-image').click();
      }
      break;

      case 39: // right
      if (($('#image-gallery').data('bs.modal') || {})._isShown && $('#show-next-image').is(":visible")) {
      	$('#show-next-image').click();
      }
      break;

      default:
        return; // exit this handler for other keys
      }
    e.preventDefault(); // prevent the default action (scroll / move caret)
  });

</script>